image: node:alpine

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

stages:
  - install
  - test
  - build
  - deploy

install:
  stage: install
    only:
      - merge_requests
    script:
      - npm install

test:
  stage: test
    only:
      - merge_requests
    script:
      - npm ci

build:
  stage: build
    only:
      - development
    script:
      - echo "Build"

deploy:
  stage: deploy
    only:
      - master
    script:
      - echo "Deployed"
